@Dsw2026Ej15.Api_HostAddress = http://localhost:5162

### Crear un doctor
POST {{Dsw2026Ej15.Api_HostAddress}}/api/doctors
Content-Type: application/json

{
  "name": "Juan Pérez",
  "licenseNumber": "MAT-12345",
  "specialityId": "8a1f3b78-3f66-4d68-8d6e-1c5b9c7a2f41"
}

###